language: ruby

rvm:
  - 2.5.1

services:
  - postgresql

before_script:
  - bin/rails db:create
  - bin/rails db:migrate

script:
  - bin/rails test

deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"